apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-card-chargegsurf-fake
  description: Responsible for performing a card payment.
spec:
  type: service
  lifecycle: deprecated
  owner: squad-cartao
  subcomponentOf:
    - component: walletmanager-db-fake

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: walletmanager-db-fake
  description: Stores hashes of cards saved in the wallet by clientId
spec:
  type: database
  owner: squad-cartao

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mapping-db
  description: The database used for mapping purposes
spec:
  type: database
  owner: squad-cartao
